### PR TITLE
Return empty string instead of crashing when UCD_TO_SPECTRAL_NAME lookup failed

### PR DESCRIPTION
**Pull request by pllim**
## Description

Without this patch, loading an uncalibrated 2D spectrum without wavelength axis will crash.

### CODE REVIEW

**Comment by dhomeier** [comment]
Thanks, fix looks quite uncontroversial, except that I am wondering if it would be better to give a default description like 'Undefined' or 'Dimensionless'. I suppose the method is entirely for informational purposes, so it's largely up to taste?

I also noticed an unrelated typo in
https://github.com/glue-viz/glue-astronomy/blob/b9b9d8fb30e16c92ca7347abbfa4fba2676bb654/glue_astronomy/translators/spectrum1d.py#L32
that would likely result in a lookup failure.

**Comment by dhomeier** [comment]
Hmm, maybe I stand corrected on that last one – that **is** how it was introduced in
https://github.com/astropy/astropy/blob/main/astropy/wcs/wcsapi/fitswcs.py#L120
I guess since it is `custom:` we may call it any way we like; still wondering if it makes sense to use different spellings for related types.

**Comment by pllim** [comment]
I'm not familiar with the FITS standards to know what that would be.

**Comment by dhomeier** [comment]
The other translations were originally implemented as part of [APE14](https://github.com/astropy/astropy-APEs/blob/main/APE14.rst#common-ucd1-names-for-physical-types), but for the custom/undefined types there are of course no specifications in the UCD+ vocabulary.
I think the naming of `beta` as Doppler velocity would better be dealt with in an `astropy.wcs` issue.

**Comment by pllim** [comment]
@dhomeier , so is there a specific change you want me to make here? I am a little confused.

**Comment by dhomeier** [comment]
Having looked at fitswcs again, I suppose without a recognised `physical_type` the axis could be anything, so no label seems OK. With the formatting fixed this should be good to goo, thanks!

**Comment by pllim** [comment]
I applied your suggestion. Thanks for the review!

**Comment by pllim** [comment]
I don't think we can remove the parenthesis for Python 3.7?

```
INTERNALERROR>   File ".../glue_astronomy/translators/spectrum1d.py", line 117
INTERNALERROR>     return UCD_TO_SPECTRAL_NAME.get(self.spectral_wcs.world_axis_physical_types[0], ''), *names
```

**Comment by dhomeier** [comment]
Uh, another thing I cannot test on macOS 12... better to break the line then, I think (on black comes over us one day, max line length is probably going to change again anyway).

**Comment by pllim** [comment]
Thanks! Is a release planned soon?

**Pull request merged**
