### PR TITLE
Fixed return type and shape for pixel <-> world conversions in SpectralCoordinates

### PR DESCRIPTION
**Pull request by astrofrog**
The pixel <-> world methods should return single scalars/arrays not tuples in order to be APE-14-compliant.

### CODE REVIEW

**Comment by pllim** [comment]
Is it a concern that the CI fails here?

**Comment by pllim** [comment]
I tried this out at https://github.com/spacetelescope/jdaviz/pull/1968 but now it fails with an even more obscure error:

`AttributeError: 'numpy._ArrayFunctionDispatcher' object has no attribute '__code__'`

https://github.com/spacetelescope/jdaviz/actions/runs/3959079839/jobs/6781436962

**Comment by dhomeier** [comment]
spectrum1d test was still expecting the old, incorrect shape.

**Comment by pllim** [comment]
Oh wait... `glue-astronomy==0.5.1` ... I think I have to remove pin because I am trying to install it from fork branch that has no tags. Hold on.

**Review by dhomeier — APPROVED** [review]
Fixes the `jdaviz` test suite for me (macos-py310), but should probably wait for @pllim's test PR to at least run.

**Pull request merged**
